name: Flutter Tag Build (Direct)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch, tag, or commit SHA to build"
        required: true
        default: connector-id-feature-v13
      upload-artifact:
        description: "Upload build artifacts"
        type: boolean
        default: true

env:
  SCITER_RUST_VERSION: "1.75"
  RUST_VERSION: "1.75"
  MAC_RUST_VERSION: "1.81"
  CARGO_NDK_VERSION: "3.1.2"
  SCITER_ARMV7_CMAKE_VERSION: "3.29.7"
  SCITER_NASM_DEBVERSION: "2.15.05-1"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  ANDROID_FLUTTER_VERSION: "3.24.5"
  FLUTTER_ELINUX_VERSION: "3.16.9"
  TAG_NAME: "${{ inputs.branch }}"
  UPLOAD_ARTIFACT: "${{ inputs.upload-artifact }}"
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  ARMV7_VCPKG_COMMIT_ID: "6f29f12e82a8293156836ad81cc9bf5af41fe836"
  VERSION: "1.4.5"
  NDK_VERSION: "r27c"
  SIGN_BASE_URL: "${{ secrets.SIGN_BASE_URL }}-2"

jobs:
  generate-bridge:
    name: Generate flutter-rust bridge
    runs-on: ubuntu-22.04
    env:
      CHECKOUT_REF: ${{ inputs.branch }}
      CARGO_EXPAND_VERSION: "1.0.95"
      FLUTTER_RUST_BRIDGE_VERSION: "1.80.1"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_REF }}
          submodules: recursive

      - name: Install prerequisites
        run: |
          sudo apt-get install ca-certificates -y
          sudo apt-get update -y
          sudo apt-get install -y \
            clang \
            cmake \
            curl \
            gcc \
            git \
            g++ \
            libclang-dev \
            libgtk-3-dev \
            llvm-dev \
            nasm \
            ninja-build \
            pkg-config \
            wget

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-unknown-linux-gnu
          components: "rustfmt"

      - uses: Swatinem/rust-cache@v2
        with:
          prefix-key: bridge-${{ runner.os }}

      - name: Cache Bridge
        id: cache-bridge
        uses: actions/cache@v3
        with:
          path: /tmp/flutter_rust_bridge
          key: bridge-${{ runner.os }}

      - name: Install flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: Install flutter rust bridge deps
        shell: bash
        run: |
          cargo install cargo-expand --version ${{ env.CARGO_EXPAND_VERSION }} --locked
          cargo install flutter_rust_bridge_codegen --version ${{ env.FLUTTER_RUST_BRIDGE_VERSION }} --features "uuid" --locked
          pushd flutter && sed -i -e 's/extended_text: 14.0.0/extended_text: 13.0.0/g' pubspec.yaml && flutter pub get && popd

      - name: Run flutter rust bridge
        run: |
          ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/macos/Runner/bridge_generated.h
          cp ./flutter/macos/Runner/bridge_generated.h ./flutter/ios/Runner/bridge_generated.h

      - name: Upload bridge artifact
        uses: actions/upload-artifact@master
        with:
          name: bridge-artifact
          path: |
            ./src/bridge_generated.rs
            ./src/bridge_generated.io.rs
            ./flutter/lib/generated_bridge.dart
            ./flutter/lib/generated_bridge.freezed.dart
            ./flutter/macos/Runner/bridge_generated.h
            ./flutter/ios/Runner/bridge_generated.h

  build-topmost-window:
    name: Build RustDeskTempTopMostWindow
    runs-on: windows-2022
    needs: generate-bridge
    env:
      CHECKOUT_REF: ${{ inputs.branch }}
      project_path: WindowInjection/WindowInjection.vcxproj
    steps:
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Download the source code
        run: git clone https://github.com/rustdesk-org/RustDeskTempTopMostWindow RustDeskTempTopMostWindow

      - name: Build the project
        run: |
          cd RustDeskTempTopMostWindow
          git checkout 53b548a5398624f7149a382000397993542ad796
          msbuild ${{ env.project_path }} -p:Configuration=Release -p:Platform=x64 /p:TargetVersion=Windows10

      - name: Archive build artifacts
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@master
        with:
          name: topmostwindow-artifacts
          path: |
            ./RustDeskTempTopMostWindow/WindowInjection/x64/Release/WindowInjection.dll

  build-windows:
    name: Build rustdesk windows
    needs: [generate-bridge, build-topmost-window]
    runs-on: windows-2022
    env:
      CHECKOUT_REF: ${{ inputs.branch }}
      TAG_NAME: ${{ inputs.branch }}
      UPLOAD_ARTIFACT: ${{ inputs.upload-artifact }}
    steps:
      - name: Export cache env vars
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.CHECKOUT_REF }}
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Download RustDeskTempTopMostWindow artifact
        uses: actions/download-artifact@master
        with:
          name: topmostwindow-artifacts
          path: ./RustDeskTempTopMostWindow/WindowInjection/x64/Release

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: "stable"
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Replace engine with rustdesk custom flutter engine
        run: |
          flutter doctor -v
          flutter precache --windows
          Invoke-WebRequest -Uri https://github.com/rustdesk/engine/releases/download/main/windows-x64-release.zip -OutFile windows-x64-release.zip
          Expand-Archive -Path windows-x64-release.zip -DestinationPath windows-x64-release
          mv -Force windows-x64-release/*  C:/hostedtoolcache/windows/flutter/stable-${{ env.FLUTTER_VERSION }}-x64/bin/cache/artifacts/engine/windows-x64-release/

      - name: Patch flutter
        shell: bash
        run: |
          cp .github/patches/flutter_3.24.4_dropdown_menu_enableFilter.diff $(dirname $(dirname $(which flutter)))
          cd $(dirname $(dirname $(which flutter)))
          [[ "3.24.5" == ${{env.FLUTTER_VERSION}} ]] && git apply flutter_3.24.4_dropdown_menu_enableFilter.diff

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.SCITER_RUST_VERSION }}
          targets: x86_64-pc-windows-msvc
          components: "rustfmt"

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}
          doNotCache: false

      - name: Install vcpkg dependencies
        env:
          VCPKG_DEFAULT_HOST_TRIPLET: x64-windows-static
        run: |
          if ! $Env:VCPKG_ROOT/vcpkg install --triplet x64-windows-static --x-install-root="$Env:VCPKG_ROOT/installed" {
            Get-ChildItem -Path "$Env:VCPKG_ROOT" -Filter *.log -Recurse | ForEach-Object {
              Write-Host "$_"; Write-Host "======"; Get-Content "$_"; Write-Host "======"; Write-Host
            }
            exit 1
          }

      - name: Force clean build (v4)
        shell: bash
        working-directory: ${{ github.workspace }}
        env:
          CARGO_INCREMENTAL: "0"
        run: cargo clean

      - name: Build rustdesk
        env:
          CARGO_INCREMENTAL: "0"
        run: |
          python3 .\build.py --portable --hwcodec --flutter --vram --skip-portable-pack
          mv ./flutter/build/windows/x64/runner/Release ./rustdesk
          Invoke-WebRequest -Uri https://github.com/rustdesk-org/rdev/releases/download/usbmmidd_v2/usbmmidd_v2.zip -OutFile usbmmidd_v2.zip
          Expand-Archive usbmmidd_v2.zip -DestinationPath .
          Remove-Item -Path usbmmidd_v2\Win32 -Recurse
          Remove-Item -Path "usbmmidd_v2\deviceinstaller64.exe", "usbmmidd_v2\deviceinstaller.exe", "usbmmidd_v2\usbmmidd.bat"
          mv -Force .\usbmmidd_v2 ./rustdesk
          try {
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/rustdesk_printer_driver_v4-1.4.zip -OutFile rustdesk_printer_driver_v4-1.4.zip
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/printer_driver_adapter.zip -OutFile printer_driver_adapter.zip
            Invoke-WebRequest -Uri https://github.com/rustdesk/hbb_common/releases/download/driver/sha256sums -OutFile sha256sums
            $checksum_driver = (Select-String -Path .\sha256sums -Pattern '^([a-fA-F0-9]{64}) \*rustdesk_printer_driver_v4-1.4\.zip$').Matches.Groups[1].Value
            $downloadsum_driver = Get-FileHash -Path rustdesk_printer_driver_v4-1.4.zip -Algorithm SHA256
            $checksum_adapter = (Select-String -Path .\sha256sums -Pattern '^([a-fA-F0-9]{64}) \*printer_driver_adapter\.zip$').Matches.Groups[1].Value
            $downloadsum_adapter = Get-FileHash -Path printer_driver_adapter.zip -Algorithm SHA256
            if ($checksum_driver -eq $downloadsum_driver.Hash -and $checksum_adapter -eq $downloadsum_adapter.Hash) {
              Write-Output "rustdesk_printer_driver_v4-1.4, checksums match, extract the file."
              Expand-Archive rustdesk_printer_driver_v4-1.4.zip -DestinationPath .
              mkdir ./rustdesk/drivers
              mv -Force .\rustdesk_printer_driver_v4-1.4 ./rustdesk/drivers/RustDeskPrinterDriver
              Expand-Archive printer_driver_adapter.zip -DestinationPath .
              mv -Force .\printer_driver_adapter.dll ./rustdesk
            } elseif ($checksum_driver -ne $downloadsum_driver.Hash) {
              Write-Output "rustdesk_printer_driver_v4-1.4, checksums do not match, ignore the file."
            } else {
              Write-Output "printer_driver_adapter.dll, checksums do not match, ignore the file."
            }
          } catch {
            Write-Host "Ignore the printer driver error."
          }

      - name: Upload rustdesk artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@master
        with:
          name: rustdesk-unsigned-windows-x86_64
          path: rustdesk
